version: '3'
services:
  influx:
    image: influxdb:alpine
    ports:
      - 8086:8086
    deploy:
      resources:
        limits:
          memory: 100M
    environment:
      - INFLUXDB_DB=mes
    networks:
      - inf
  
  chronograf:
    image: chronograf:alpine
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - inf

  generator:
    image: lertatraining/k8sfirststeps:0.1
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 5M
    networks:
      - inf
    depends_on:
      - influx

networks:
  inf: