apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "red.fullname" . }}
  labels:
    chart: {{ include "red.chart" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
