apiVersion: v1
kind: Secret
metadata:
  name: {{ include "red.fullname" . }}-encryption
  labels:
    chart: {{ include "red.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  useMeForEncryption: dGhpcyBpcyB2ZXJ5IHNlY3JldA==



