apiVersion: v1
kind: Service
metadata:
  name: {{ include "red.fullname" . }}
  labels:
    chart: {{ include "red.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    colour: red
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
