apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/version: "2"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/version: "2"
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.0
        ports:
        - name: api
          containerPort: 8086
          protocol: TCP
        env:
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: admin
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: admin
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: testing-please-ignore
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: test
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 1d
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: 1234567890
