apiVersion: v1
kind: Service
metadata:
  name: generator
  labels:
    component: generator
spec:
  selector:
    component: generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
