apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
  labels:
    component: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      component: generator
  template:
    metadata:
      labels:
        component: generator
    spec:
      containers:
        - name: generator
          image: kskitek/k8sfirststeps:random-latest
          env:
            - name: INFLUX_URL
              value: http://10.244.0.22:8086
          ports:
            - containerPort: 8080
