apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx
  labels:
    component: influx
    type: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx
  labels:
    component: influx
    type: db
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/kind/influx
