apiVersion: v1
kind: Service
metadata:
  name: influx
  labels:
    component: influx
    type: db
spec:
  selector:
    component: influx
    type: db
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
