apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    component: influx
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
        component: influx
        type: db
  template:
    metadata:
      labels:
        component: influx
        type: db
    spec:
      containers:
      - name: influx
        image: influxdb:2.0
        ports:
        - containerPort: 8086
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: firstuser
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: verysecret
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influx
              key: token
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: illuminati
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: leakybucket
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 2d
        volumeMounts:
          - name: data
            mountPath: /var/lib/influxdb2
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: influx
