apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: influx
  name: influx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influx
    spec:
      containers:
      - env:
        - name: INFLUXDB_DB
          value: mes
        image: influxdb
        name: influx
        ports:
        - containerPort: 8086
        resources:
          limits:
            memory: "104857600"
      restartPolicy: Always
status: {}
