apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generator.fullname" . }}
  labels:
    component: generator
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: generator
  template:
    metadata:
      labels:
        component: generator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GENERATOR_MIN
              value: {{ .Values.min | quote }}
            - name: GENERATOR_MAX
              value: {{ .Values.max | quote }}
            - name: INFLUX_URL
              value: {{ .Values.influx.url }}
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influx
                  key: token
            {{- range $key, $v := .Values.envs }}
            - name: {{ $key | upper }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
